get "/", forward: "/WEB-INF/pages/index.gtpl"
get "/datetime", forward: "/datetime.groovy"
get "/favicon.ico", redirect: "/images/google-app-engine-groovy.png"
get "/cron/ping", forward: "/ping.groovy"
get "/cron/pong", forward: "/pong.groovy"
get "/cron/parse-scoreboard", forward: "/parseScoreboard.groovy"
get "/cron/parse-schedule", forward: "/parseSchedule.groovy"
get "/cron/update-scoreboard", forward: "/updateScoreboard.groovy"
get "/cron/update-schedule", forward: "/updateSchedule.groovy"

get "/stats/team-stats", forward: "/teamStats.groovy"